controllers/routes.py
import json
import math
import random

import numpy
from flask import Blueprint, render_template, request, session, redirect, url_for

import globalvars
from classifier.product_classifier import ProductCategoryClassifier, strip_tags
from models import db
from models.productmodel import Product

app = Blueprint("routes", __name__)


@app.route("/")
def index():
    return render_template("index.html")


@app.route("/pasang-iklan", methods=["GET"])
def add_ads():
    return render_template("add-ads.html")


@app.route("/pasang-iklan", methods=["POST"])
def save_ads():
    product_main = dict()
    product_main["company"] = request.form.get("company")
    product_main["category"] = request.form.get("category")
    product_main["subcategory"] = request.form.get("subcategory")
    product_main["product_name"] = request.form.get("product_name")
    product_main["price"] = request.form.get("price")
    product_main["image_link"] = request.form.get("image_link")
    product_main["product_url"] = None
    product_main["description"] = request.form.get("description")
    product_detail = dict()
    product_detail["name"] = request.form.get("name")
    product_detail["email"] = request.form.get("email")
    product_detail["phone_number"] = request.form.get("phone_number")
    product = Product(**product_main)
    product.set_owner(**product_detail)
    db.session.add(product)
    db.session.commit()
    return redirect(url_for('routes.get_product_desc', product_id=product.id))


NUMBER_OF_ITEMS_IN_PAGE = 24


@app.route("/category/<category_name>")
def list_products_by_category(category_name):
    page_number = request.args.get('page')
    if page_number is None:
        page_number = 1
    else:
        page_number = int(page_number)
    subcategories = Product.query \
        .with_entities(Product.subcategory) \
        .filter_by(category=" " + category_name) \
        .distinct() \
        .all()
    products_pagination = Product.query \
        .filter_by(category=" " + category_name) \
        .paginate(page_number, NUMBER_OF_ITEMS_IN_PAGE)
    products = products_pagination.items
    number_of_products = products_pagination.total
    number_of_pages = int(math.ceil(number_of_products / NUMBER_OF_ITEMS_IN_PAGE))
    pagination_start = max(page_number - 3, 1)
    pagination_end = min(number_of_pages, pagination_start + 6)
    return render_template("product-list.html",
                           category=category_name,
                           subcategories=subcategories,
                           products=products,
                           number_of_pages=number_of_pages,
                           curr_page_num=page_number,
                           pagination_start=pagination_start,
                           pagination_end=pagination_end
                           )


@app.route("/category/<category_name>/subcategory/<subcategory_name>")
def list_products_by_subcategory(category_name, subcategory_name):
    page_number = request.args.get('page')
    if page_number is None:
        page_number = 1
    else:
        page_number = int(page_number)
    subcategories = Product.query \
        .with_entities(Product.subcategory) \
        .filter_by(category=" " + category_name) \
        .distinct() \
        .all()
    products_pagination = Product.query \
        .filter_by(category=" " + category_name, subcategory=subcategory_name) \
        .paginate(page_number, NUMBER_OF_ITEMS_IN_PAGE)
    products = products_pagination.items
    number_of_products = products_pagination.total
    number_of_pages = int(math.ceil(number_of_products / NUMBER_OF_ITEMS_IN_PAGE))
    pagination_start = max(page_number - 3, 1)
    pagination_end = min(number_of_pages, pagination_start + 6)
    print(pagination_start, pagination_end)
    return render_template("product-list.html",
                           category=category_name,
                           subcategories=subcategories,
                           products=products,
                           number_of_pages=number_of_pages,
                           curr_page_num=page_number,
                           pagination_start=pagination_start,
                           pagination_end=pagination_end
                           )


@app.route("/product/<product_id>")
def get_product_desc(product_id):
    product = Product.query.get_or_404(product_id)
    product.description = strip_tags(product.description)
    return render_template("product-desc.html", product=product)


@app.route('/admin')
def get_admin():
    limit = 100
    product_arr = list()
    with open("scraper/scrapeddata/tokopedia.json") as json_file:
        tokopedia_products = json.load(json_file)
        random.seed(1)
        sample_idx_list = numpy.random.choice(range(len(tokopedia_products)), size=limit, replace=False)
        for sample_idx in sample_idx_list:
            product_json = tokopedia_products[sample_idx]
            product_arr.append(product_json)
            product_json['id'] = len(product_arr)
        session["sample_indices"] = sample_idx_list.tolist()
    return render_template('admin.html', products=product_arr)


@app.route("/admin/result")
def get_admin_result():
    sample_indices = session.pop("sample_indices", None)
    if sample_indices is None:
        return get_admin()
    classified_product_arr = list()
    classifier = globalvars.cls
    with open("scraper/scrapeddata/tokopedia.json") as json_file:
        tokopedia_products = json.load(json_file)
        for sample_idx in sample_indices:
            product_json = tokopedia_products[sample_idx]
            (category, subcategory) = classifier.classify([(product_json["product_name"], product_json["description"])])[0]
            product_json["pred_category"] = category
            product_json["pred_subcategory"] = subcategory
            classified_product_arr.append(product_json)
    return render_template("admin-res.html", products=classified_product_arr)

templates/add-ads.html
{% include 'header.html' %}
<body id="home">
{% include 'navbar.html' %}

<!-- Contact -->
<div id="contact" class="container">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 text-center wrap_title">
                <h3>Pasang Iklan</h3>
                <p class="lead" style="margin-top:0">Pasang iklan anda disini.</p>
            </div>
            <form role="form" action="" method="post">
                <div class="col-md-10 col-md-offset-1 text-center wrap_title">
                    <div class="row">
                        <div class="form-group">
                            <div class="col-md-2">
                                <label>Judul Iklan</label>
                            </div>
                            <div class="col-md-8">
                                <div class="input-group">
                                    <input type="text" class="form-control" name="product_name" id="product-name"
                                           placeholder="Judul iklan" required>
                                    <span class="input-group-addon"><i
                                            class="glyphicon glyphicon-ok form-control-feedback"></i></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <br>

                    <div class="row">
                        <div class="form-group">
                            <div class="col-md-2">
                                <label for="InputMessage">Deksripsi Iklan</label>
                            </div>
                            <div class="col-md-8">
                                <div class="input-group">
                                    <textarea name="description" id="description" class="form-control" rows="5"
                                              required></textarea>
                                    <span class="input-group-addon"><i
                                            class="glyphicon glyphicon-ok form-control-feedback"></i></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <br>


                    <div class="row">
                        <div class="form-group">
                            <div class="col-md-2">
                                <label for="InputName">Kategori</label>
                            </div>
                            <div class="col-md-3">
                                <div class="col-md-12 input-group">
                                    <input type="text" class="form-control" name="category" id="category"
                                           placeholder="Kategori" required>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="col-md-12 input-group">
                                    <input type="text" class="form-control" name="subcategory" id="subcategory"
                                           placeholder="Subkategori" required>
                                    <span class="input-group-addon"><i
                                            class="glyphicon glyphicon-ok form-control-feedback"></i></span>
                                </div>
                            </div>
                            <div class="col-md-1">
                                <div class="input-group">
                                    <a href="#" id="auto-categorization"
                                       class="btn wow tada btn-embossed btn-info pull-right">
                                        Auto Categorization
                                    </a>
                                </div>
                            </div>

                        </div>
                    </div>
                    <br>

                    <div class="row">
                        <div class="form-group">
                            <div class="col-md-2">
                                <label for="InputName">Harga</label>
                            </div>
                            <div class="col-md-8">
                                <div class="input-group">
                                    <input type="text" class="form-control" name="price" id="Harga"
                                           placeholder="Harga" required>
                                    <span class="input-group-addon"><i
                                            class="glyphicon glyphicon-ok form-control-feedback"></i></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <br>

                    <div class="row">
                        <div class="form-group">
                            <div class="col-md-2">
                                <label for="InputName">Nama</label>
                            </div>
                            <div class="col-md-8">
                                <div class="input-group">
                                    <input type="text" class="form-control" name="name" id="name" placeholder="Nama"
                                           required>
                                    <span class="input-group-addon"><i
                                            class="glyphicon glyphicon-ok form-control-feedback"></i></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <br>

                    <div class="row">
                        <div class="form-group">
                            <div class="col-md-2">
                                <label for="InputEmail">Email</label>
                            </div>
                            <div class="col-md-8">
                                <div class="input-group">
                                    <input type="email" class="form-control" id="email" name="email"
                                           placeholder="Enter Email" required>
                                    <span class="input-group-addon"><i
                                            class="glyphicon glyphicon-ok form-control-feedback"></i></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <br>

                    <div class="row">
                        <div class="form-group">
                            <div class="col-md-2">
                                <label for="InputName">No Telepon/HP</label>
                            </div>
                            <div class="col-md-8">
                                <div class="input-group">
                                    <input type="text" class="form-control" name="phone_number" id="Telepon"
                                           placeholder="No Telepon" required>
                                    <span class="input-group-addon"><i
                                            class="glyphicon glyphicon-ok form-control-feedback"></i></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <br>

                    <input type="submit" name="submit" id="submit" value="Submit"
                           class="btn wow tada btn-embossed btn-primary pull-right">
                </div>
            </form>
        </div>
    </div>
</div>

{% include 'footer.html' %}
<script src="{{ url_for("static", filename="js/jquery-1.9.1.min.js") }}"></script>
<script>
    $("#auto-categorization").click(function() {
        $.ajax({
            url: "/api/categorize",
            method: "POST",
            data: {
                product_name: $("#product-name").val(),
                description: $("#description").val()
            }
        }).done(function(data) {
            $("#category").val(data.category);
            $("#subcategory").val(data.subcategory);
        });
    });
</script>
</body>


</html>

templates/admin-res.html
{% include 'header.html' %}
<body id="home">
{% include 'navbar.html' %}

<!-- Admin page -->
<br>
<div class=" row">
    <div class="col-md-10 col-md-offset-1 text-center wrap_title">
        <h3>Admin Page</h3>
    </div>
</div>
<hr>
<div class="container">
    <table class="table table-striped">
        <thead>
        <tr>
            <th style="width: 20px"><h4>No.</h4></th>
            <th><h4>Nama Produk</h4></th>
            <th><h4>Kategori</h4></th>
            <th><h4>Subkategori</h4></th>
            <th><h4>Prediksi kategori</h4></th>
            <th><h4>Prediksi subkategori</h4></th>
        </tr>
        </thead>
        <tbody>
        {% for product in products %}
            <tr>
                <th>{{ product['id'] }}</th>
                <th>{{ product['product_name'] }}</th>
                <th>{{ product['category'] }}</th>
                <th>{{ product['subcategory'] }}</th>
                <th>{{ product['pred_category'] }}</th>
                <th>{{ product['pred_subcategory'] }}</th>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
</body>
</html>

templates/admin.html
{% include 'header.html' %}
<body id="home">
{% include 'navbar.html' %}

<!-- Admin page -->
	 <br>
    <div class=" row">
            <div class="col-md-10 col-md-offset-1 text-center wrap_title">
				<h3>Admin Page</h3>
			</div>
    </div>
    <hr></hr>
    <div class="container">
        <table class="table table-striped">
        <thead>
            <tr>
                <th style="width: 20px"><h4>No.</h4></th>
                <th><h4>Nama Produk</h4></th>
                <th><h4>Kategori</h4></th>
                <th><h4>Subkategori</h4></th>
                <th><h4>Source</h4></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th>**increment 1-N**</th>
                <th>**isi nama produk**</th>
                <th>**isi kategori**</th>
                <th>**isi subkategori**</th>
                <th><a href="">Link</a></th>
            </tr>
        </tbody>
        </table>
        <input type="submit" name="submit" id="submit" value="Categorize" class="btn wow tada btn-embossed btn-primary pull-right">
    </div>


</body>

</html>

templates/adminPage.html
{% include 'header.html' %}
<body id="home">
{% include 'navbar.html' %}

<!-- Admin page -->
	<div id="contact" class="intro-header">
		<div class="container">
			<div class="row">
			
			<div class="col-md-6 col-md-offset-3 text-center wrap_title">
				<h2>Admin Page</h2>
			</div>
			
			<form role="form" action="" method="post" >
				<div class="col-md-10 col-md-offset-1 text-center wrap_title">
					<img  src="{{ url_for("static", filename="img/icon/config.svg") }}"
                         alt="Generic placeholder image" style="width: 30%">

					<div class="row">
                        <br>
						<div class="form-group">
							<div class="col-md-2">
								<h4 for="InputName">Scraping URL</h4>
							</div>
							<div class="col-md-10">
								<div class="input-group">
									<input type="text" class="form-control" name="Scraping" id="Scraping" placeholder="URL" required>
									<span class="input-group-addon"><i class="glyphicon glyphicon-ok form-control-feedback"></i></span>
                                    <input type="submit" name="submit" id="submit" value="Scrape" class="btn wow tada btn-embossed btn-primary pull-right">
								</div>

							</div>
						</div>

					</div>
				</div>
			</form>
		</div>
	</div>
</div>

</body>

</html>

templates/deskripsiEcommerce.html
{% include 'header.html' %}

<body id="home">
{% include 'navbar.html' %}
{#	<!-- Preloader -->#}
{#	<div id="preloader">#}
{#		<div id="status"></div>#}
{#	</div>#}

<iframe src="https://www.tokopedia.com/catalog/50762/nokia-215-dual-sim" style="width:100vw; height:100vh;">
    Your browser doesn't support iframes
</iframe>

</body>

templates/deskripsiProduk.html
{% include 'header.html' %}

<body id="home">
{% include 'navbar.html' %}
	<!-- Preloader -->
	<div id="preloader">
		<div id="status"></div>
	</div>

	<br>
	<!-- deskripsiProduk -->
	<div id="deskripsiProduk" class="container" >
			<div class="col-md-offset-1 row">
				<div class=" row  col-md-10 alert alert-success">
					<div class="row col-md-offset-1">
						<div class="col-md-7"><h3>Nama Produk</h3></div>
						<div class="col-md-offset-1 col-md-3 text-center"><div class="alert alert-danger"><h4>Rp. 80.000.000</h4></div></div>
					</div>
					<div class="row col-md-10 col-md-offset-1 alert alert-warning">
							<div class="col-md-5"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Jakarta, DKI Jakarta</div>
							<div class="col-md-5"><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>087887401321</div>
					</div>
				</div>
			</div>
			<div class="col-md-offset-1 row">
				<div class=" row  col-md-10 jumbotron">
					<div class="col-md-7"><img src="https://www.enterprise.com/content/dam/global-vehicle-images/cars/FORD_FOCU_2012-1.png" alt="..." width="70%"></div>
					<div class="col-md-5"><h3>Deskripsi Produk</h3>
                        <h6>
                        Jual mobil kesayangan nih Xtrail 2009 AT triptonic 2000cc Irit.. Km 59rb'an on going. Asli no tipu2.
                        Rawatan Nissan dan Jasmin (nissan lover's pasti tau kredibilitasnya).AC duinginnn...Mesin kering kerontang..
                        Warna silver,Kaki2 ok matic baru ganti, ban 85%.Audio touch screen dengan head rest monitor untuk yang di belakang.
                        Kaca FILM 3M Crystaline, ademmmm...Semua normal, Minus lecet dikit di pintu bawah kiri.Pajak hidup, Bintaro.Lokasi mobil seputar BSD
                        </h6>
                    </div>
				</div>
			</div>
			<!-- <div class="col-md-7 col-md-offset-1 text-left wrap_title jumbotron" style="">
					<div class="row">
						<h3>Nama Produk</h3>
					</div>
					<div class="row alert alert-warning">
						<div class="col-md-4">Jakarta, DKI Jakarta</div>
						<div class="col-md-2">087887401321</div>
					</div>
					<div class="row">
						<img src="https://www.enterprise.com/content/dam/global-vehicle-images/cars/FORD_FOCU_2012-1.png" alt="..." width="70%">
					</div>
			</div>
			<div class="col-md-3 text-center wrap_title row alert alert-success">
					<div class="alert alert-danger"><h4>Rp. 80.000.000</h4></div>
			</div>		 -->
	</div>


{% include 'footer.html' %}
</body>

templates/index.html
{% include 'header.html' %}
<body>
{% include 'navbar.html' %}

<!-- Preloader -->
<div id="preloader">
    <div id="status"></div>
</div>

<!-- FullScreen -->
<div class="intro-header">
    <div class="col-xs-12 text-center abcen1">
        <h1 class="h1_home wow fadeIn" data-wow-delay="0.4s">Five-Footer</h1>
    </div>
    <!-- /.container -->
    <div class="col-xs-12 text-center abcen wow fadeIn">
        <div class="button_down ">
            <a class="imgcircle wow bounceInUp" data-wow-duration="1.5s" href="#kategori-produk">
                <img class="img_scroll" src="{{ url_for("static", filename="img/icon/circle.png") }}" alt="">
            </a>
        </div>
    </div>
</div>


<!-- Daftar kategori -->
<div id="kategori-produk" class="content-section-b">
    <div class="container">
        <div class="col-md-6 col-md-offset-3 text-center wrap_title">
            <h2>Produk</h2>
            <p class="lead" style="margin-top:0">Kategori produk.</p>
        </div>

        <div class="row">
            <div class="col-md-offset-1 col-md-12 wow fadeInDown text-center">
                <a href="{{ url_for("routes.list_products_by_category", category_name="Mobil") }}">
                    <div class="col-sm-2 wow fadeInDown text-center" id="Mobil">
                        <img class="rotate" src="{{ url_for("static", filename="img/icon/large-car.png") }}"
                             alt="Generic placeholder image" style="width:65%">
                        <h3>Mobil</h3>
                    </div>
                </a>
                <a href="{{ url_for("routes.list_products_by_category", category_name="Motor") }}">
                    <div class="col-sm-2 wow fadeInDown text-center">
                        <img class="rotate" src="{{ url_for("static", filename="img/icon/motorcycle.png") }}"
                             alt="Generic placeholder image"
                             style="width:65%">
                        <h3>Motor</h3>
                    </div>
                </a>
                <a href="{{ url_for("routes.list_products_by_category", category_name="Properti") }}">
                    <div class="col-sm-2 wow fadeInDown text-center">
                        <img class="rotate" src="{{ url_for("static", filename="img/icon/building.png") }}"
                             alt="Generic placeholder image"
                             style="width:65%">
                        <h3>Properti</h3>
                    </div>
                </a>
                <a href="{{ url_for("routes.list_products_by_category", category_name="Keperluan Pribadi") }}">
                    <div class="col-sm-2 wow fadeInDown text-center">
                        <img class="rotate" src="{{ url_for("static", filename="img/icon/heels.png") }}"
                             alt="Generic placeholder image"
                             style="width:65%">
                        <h3>Keperluan Pribadi</h3>
                    </div>
                </a>
                <a href="{{ url_for("routes.list_products_by_category", category_name="Elektronik & Gadget") }}">
                    <div class="col-sm-2 wow fadeInDown text-center">
                        <img class="rotate" src="{{ url_for("static", filename="img/icon/laptop.svg") }}"
                             alt="Generic placeholder image">
                        <h3>Elektronik & Gadget</h3>
                    </div>
                </a>
            </div><!-- /.div 12 col -->
        </div><!-- /.row -->

        <div class="row">
            <div class="col-md-offset-1 col-sm-12 wow fadeInDown text-center">

                <a href="{{ url_for("routes.list_products_by_category", category_name="Hobi & Olahraga") }}">
                    <div class="col-sm-2 wow fadeInDown text-center" id="Hobi&Olahraga">
                        <img class="rotate" src="{{ url_for("static", filename="img/icon/football.svg") }}"
                             alt="Generic placeholder image">
                        <h3>Hobi & Olahraga</h3>
                    </div>
                </a>

                <a href="{{ url_for("routes.list_products_by_category", category_name="Rumah Tangga") }}">
                    <div class="col-sm-2 wow fadeInDown text-center" id="RumahTangga">
                        <img class="rotate" src="{{ url_for("static", filename="img/icon/chair.svg") }}"
                             alt="Generic placeholder image">
                        <h3>Rumah Tangga</h3>

                    </div>
                </a>
                <a href="{{ url_for("routes.list_products_by_category", category_name="Perlengkapan Bayi & Anak") }}">
                    <div class="col-sm-2 wow fadeInDown text-center" id="PerlengkapanBayi&Anak">
                        <img class="rotate" src="{{ url_for("static", filename="img/icon/stroller.png") }}"
                             alt="Generic placeholder image"
                             style="width:65%">
                        <h3>Perlengkapan Bayi & Anak</h3>
                    </div>
                </a>
                <a href="{{ url_for("routes.list_products_by_category", category_name="Kantor & Industri") }}">
                    <div class="col-sm-2 wow fadeInDown text-center" id="Kantor&Industri">
                        <img class="rotate" src="{{ url_for("static", filename="img/icon/clipboard.svg") }}"
                             alt="Generic placeholder image">
                        <h3>Kantor & Industri</h3>
                    </div>
                </a>
                <a href="{{ url_for("routes.list_products_by_category", category_name="Jasa & Lowongan Kerja") }}">
                    <div class="col-sm-2 wow fadeInDown text-center" id="Jasa&Lowongan Kerja">
                        <img class="rotate" src="{{ url_for("static", filename="img/icon/worker.ico") }}"
                             alt="Generic placeholder image"
                             style="width:65%">
                        <h3>Jasa & Lowongan Kerja</h3>
                    </div>
                </a>
            </div><!-- /.div 12 col -->
        </div><!-- /.row -->
    </div>
</div>

{% include 'footer.html' %}

<!-- JavaScript -->
<script src="{{ url_for("static", filename="js/jquery-1.10.2.js") }}"></script>
<script src="{{ url_for("static", filename="js/bootstrap.js") }}"></script>
<script src="{{ url_for("static", filename="js/owl.carousel.js") }}"></script>
<script src="{{ url_for("static", filename="js/script.js") }}"></script>
<!-- StikyMenu -->
<script src="{{ url_for("static", filename="js/stickUp.min.js") }}"></script>
<script type="text/javascript">
    jQuery(function ($) {
        $(document).ready(function () {
            $('.navbar-default').stickUp();

        });
    });
</script>
<!-- Smoothscroll -->
<script type="text/javascript" src="{{ url_for("static", filename="js/jquery.corner.js") }}"></script>
<script src="{{ url_for("static", filename="js/wow.min.js") }}"></script>
<script>
    new WOW().init();
</script>
<script src="{{ url_for("static", filename="js/classie.js") }}"></script>
<script src="{{ url_for("static", filename="js/uiMorphingButton_inflow.js") }}"></script>
<!-- Magnific Popup core JS file -->
<script src="{{ url_for("static", filename="js/jquery.magnific-popup.js") }}"></script>

</body>
</html>

templates/product-list.html
{% include 'header.html' %}

<body>
{% include 'navbar.html' %}
<br>

<div class="container ">
    <div class="row">
        <div class="col-md-12 wrap_title text-center" style="color: black;">
            <h3>{{ category }}</h3>
        </div>
        <div class="col-md-12 center-block">
            <div class="row">
                {% for subcategory in subcategories %}
                    <div class="col-sm-4 col-md-3">
                        <a href="{{ url_for("routes.list_products_by_subcategory", category_name=category, subcategory_name=subcategory[0]) }}">
                            <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span>
                            {{ subcategory[0] }}
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<hr>
<div id="product-list" class="container">
    <div class="row">
        {% for product in products %}
            <div class="col-sm-4 col-md-3">
                <a {% if product.company is not none %} href="{{ product.product_url }}" target="_blank"
                {% else %} href="{{ url_for("routes.get_product_desc", product_id=product.id) }}" {% endif %}>
                    <div class="thumbnail" style="width: 248px;height: 355px">
                        <img src="{{ product.image_link }}" style="width:100%;height: 170px;border: solid;">
                        <div class="caption">
                            <h5>{{ product.product_name }}</h5>
                            <h6>{{ product.subcategory }}</h6>
                            <h6>{{ product.price }}</h6>
                        </div>
                    </div>
                    <div class="{{ product.company }}"
                         style="width:50px;height: 50px; position: absolute; left: 0; top: 0"></div>
                </a>
            </div>
        {% endfor %}
    </div>
    <div class="row">
        <div class="col-md-12 text-center">
            <ul class="pagination">
                {% if curr_page_num != 1 %}
                    <li>
                        <a href="{{ request.path }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}
                {% for page_number in range(pagination_start, pagination_end + 1) %}
                    <li><a href="{{ request.path }}?page={{ page_number }}">{{ page_number }}</a></li>
                {% endfor %}
                {% if curr_page_num != number_of_pages %}
                    <li>
                        <a href="{{ request.path }}?page={{ number_of_pages }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
</div>

{% include 'footer.html' %}
</body>

</html>